rm(list = ls())
library(tidyverse)
library(readxl)
library(effsize)
library(gridExtra)
library(psy)
library(scales)
library(Rmisc)
library(knitr)
library(kableExtra)
library(broom)
library(reshape)
# library(SDMTools)
library(xtable)
library(lm.beta)
library(psych)
library(irr)
LongForm <- read.csv("Study 1 Long Form Codes.csv")

OverallIRR <- kappa2(LongForm[, c("SA", "MM")], "unweighted") #get kappa over all observations