rm(list = ls())
library(tidyverse)
library(readxl)
library(effsize)
library(gridExtra)
library(psy)
library(scales)
library(Rmisc)
library(knitr)
library(kableExtra)
library(broom)
library(reshape)
# library(SDMTools)
library(xtable)
library(lm.beta)
library(psych)

ABE3LongForm <- read.csv("Study 2a Long Form Codes.csv")

OverallIRR <- kappa2(ABE3LongForm[, c("SA", "WC")], "unweighted") #compute kappa over all observations