rm(list = ls())
library(tidyverse)
library(readxl)
library(effsize)
library(gridExtra)
library(psy)
library(scales)
library(Rmisc)
library(knitr)
library(kableExtra)
library(broom)
library(reshape)
# library(SDMTools)
library(xtable)
library(lm.beta)
library(psych)
library(irr)
BDTLongForm <- read.csv("Study 5a Long Form Codes.csv")

OverallIRR <- kappa2(BDTLongForm[, c("SA", "WC")], "unweighted")